In [1]:
import pandas as pd

In [5]:
messy = pd.read_csv("Data/messy_sales.csv")

In [6]:
messy.head(10)

         date     category channel             revenue
0  2025-08-01         Home   Email  152.92157037902993
1  08/02/2025  Electronics   Email   112.0047162510167
2  2025/03/08  Electronics  Search  129.36213952317217
3         NaN      Fashion   Email  167.22679597604372
4    20250805    Groceries  Search  156.02673970449902
5  2025-08-06  Electronics  Search   70.68166360370768
6  08/07/2025    Groceries   Email  128.50265252576767
7  2025/08/08  Electronics   Email   95.45928375106907
8         NaN  Electronics   Email   96.90343444619326
9    20250810  Electronics   Email  112.31795505815117

In [26]:
# Make sure everything is a string first
messy["date"] = messy["date"].astype(str)

# Case 1: YYYY-MM-DD
mask1 = messy["date"].str.match(r"^\d{4}-\d{2}-\d{2}$", na=False)
messy.loc[mask1, "date"] = pd.to_datetime(messy.loc[mask1, "date"], format="%Y-%m-%d", errors="coerce")

# Case 2: MM/DD/YYYY
mask2 = messy["date"].str.match(r"^\d{2}/\d{2}/\d{4}$", na=False)
messy.loc[mask2, "date"] = pd.to_datetime(messy.loc[mask2, "date"], format="%m/%d/%Y", errors="coerce")

# Case 3: YYYY/MM/DD
mask3 = messy["date"].str.match(r"^\d{4}/\d{2}/\d{2}$", na=False)
messy.loc[mask3, "date"] = pd.to_datetime(messy.loc[mask3, "date"], format="%Y/%m/%d", errors="coerce")

# Case 4: YYYYMMDD
mask4 = messy["date"].str.match(r"^\d{8}$", na=False)
messy.loc[mask4, "date"] = pd.to_datetime(messy.loc[mask4, "date"], format="%Y%m%d", errors="coerce")

# Finally, try a general parse on anything leftover
messy["date"] = pd.to_datetime(messy["date"], errors="coerce")

In [27]:
messy.head(15)

         date     category channel             revenue
0  2025-08-01         Home   Email  152.92157037902993
1  2025-08-02  Electronics   Email   112.0047162510167
2  2025-03-08  Electronics  Search  129.36213952317217
3         NaT      Fashion   Email  167.22679597604372
4  2025-08-05    Groceries  Search  156.02673970449902
5  2025-08-06  Electronics  Search   70.68166360370768
6  2025-08-07    Groceries   Email  128.50265252576767
7  2025-08-08  Electronics   Email   95.45928375106907
8         NaT  Electronics   Email   96.90343444619326
9  2025-08-10  Electronics   Email  112.31795505815117
10 2025-08-11       beauty  Search  104.32130713482634
11 2025-08-12  Electronics     App  143.62820520888926
12        NaT     Fashion    Email   122.8311317544098
13        NaT      fashion     Web  103.65025049478486
14 2025-08-15      Fashion  Search             missing

In [28]:
messy["category"] = messy["category"].str.strip().str.title()

In [29]:
messy["category"] = messy["category"].fillna("Unknown")

In [30]:
messy["category"].unique()

array(['Home', 'Electronics', 'Fashion', 'Groceries', 'Beauty', 'Unknown'],
      dtype=object)

In [31]:
messy["channel"] = messy["channel"].str.strip().str.title()

In [32]:
valid_channels = ["Web", "App", "Search", "Affiliate", "Email"]
messy.loc[~messy["channel"].isin(valid_channels), "channel"] = "Unknown"

In [33]:
messy["channel"].unique()

array(['Email', 'Search', 'App', 'Web', 'Unknown', 'Affiliate'],
      dtype=object)

In [55]:
pd.set_option("display.max_rows", 100)

In [56]:
messy.head(100)

         date     category    channel     revenue
0  2025-08-01         Home      Email  152.921570
1  2025-08-02  Electronics      Email  112.004716
2  2025-03-08  Electronics     Search  129.362140
3         NaT      Fashion      Email  167.226796
4  2025-08-05    Groceries     Search  156.026740
5  2025-08-06  Electronics     Search   70.681664
6  2025-08-07    Groceries      Email  128.502653
7  2025-08-08  Electronics      Email   95.459284
8         NaT  Electronics      Email   96.903434
9  2025-08-10  Electronics      Email  112.317955
10 2025-08-11       Beauty     Search  104.321307
11 2025-08-12  Electronics        App  143.628205
12        NaT      Fashion      Email  122.831132
13        NaT      Fashion        Web  103.650250
15 2025-08-16         Home      Email  110.010230
16 2025-08-17  Electronics    Unknown  144.822372
18        NaT       Beauty      Email  109.392031
19 2025-08-20       Beauty        Web   74.377128
21 2025-08-22  Electronics      Email  119.608558
23        NaT      Unknown      Email   77.735049
24 2025-08-25  Electronics        Web  168.092639
26 2025-08-27      Unknown      Email  101.372756
27        NaT      Fashion        App   94.384484
28        NaT      Fashion      Email  145.983376
29 2025-08-30  Electronics        Web  144.080763
32 2025-03-08         Home      Email   73.366428
34 2025-08-05  Electronics        Web   89.562636
35 2025-08-06       Beauty  Affiliate  104.690469
37 2025-08-08       Beauty     Search  136.071395
38        NaT         Home        Web   88.380195
39 2025-08-10  Electronics     Search   90.930917
40 2025-08-11      Fashion        App   68.543411
41 2025-08-12         Home    Unknown   57.399462
42        NaT    Groceries  Affiliate   48.811894
43        NaT       Beauty  Affiliate  158.523262
45 2025-08-16       Beauty  Affiliate   86.857771
46 2025-08-17      Fashion      Email   62.416139
47        NaT    Groceries  Affiliate  123.324711
48        NaT    Groceries        Web   51.583065
49 2025-08-20      Fashion        Web   93.617792
50 2025-08-21    Groceries        Web   73.136003
51 2025-08-22       Beauty     Search  111.607075
52        NaT       Beauty        App   84.675846
53        NaT    Groceries  Affiliate   64.581034
54 2025-08-25       Beauty      Email   99.154533
55 2025-08-26  Electronics        App  112.849956
56 2025-08-27    Groceries        Web  101.995517
58        NaT       Beauty        Web   80.970337
59 2025-08-30         Home        App   89.117765
60 2025-08-01      Unknown    Unknown   79.826187
61 2025-08-02      Fashion        Web   89.213405
62 2025-03-08      Unknown     Search   75.605612
63        NaT       Beauty      Email   48.211522
64 2025-08-05  Electronics     Search  105.322784
65 2025-08-06      Fashion     Search   87.946572
66 2025-08-07         Home     Search   51.094050
69 2025-08-10      Fashion     Search  101.558362
70 2025-08-11         Home  Affiliate  121.872717
71 2025-08-12  Electronics  Affiliate  103.869487
72        NaT    Groceries        App  134.182021
73        NaT    Groceries     Search   62.955225
75 2025-08-16       Beauty  Affiliate   79.455697
77        NaT       Beauty        App   82.634510
79 2025-08-20         Home        Web  101.684960
80 2025-08-21         Home        App   65.045505
81 2025-08-22         Home        App  127.024795
82        NaT       Beauty        Web  113.969873
83        NaT    Groceries        Web   53.912689
84 2025-08-25      Fashion        App  144.647566
85 2025-08-26      Fashion     Search  156.876675
86 2025-08-27  Electronics  Affiliate  135.363387
87        NaT         Home    Unknown   94.602255
88        NaT  Electronics  Affiliate   67.877421
89 2025-08-30  Electronics        Web  131.633552
90 2025-08-01  Electronics     Search   87.904692
91 2025-08-02    Groceries     Search  136.673352
93        NaT      Fashion  Affiliate  129.299171
94 2025-08-05      Fashion        App  110.690992
95 2025-08-06  Electronics        Web  121.197195
99 2025-08-10       Beauty        Web  112.059681

In [57]:
messy.describe(include="all")

                                 date     category channel     revenue
count                              55           80      80   80.000000
unique                            NaN            6       6         NaN
top                               NaN  Electronics   Email         NaN
freq                              NaN           21      18         NaN
mean    2025-08-05 13:05:27.272727296          NaN     NaN  103.150959
min               2025-03-08 00:00:00          NaN     NaN   48.211522
25%               2025-08-06 00:00:00          NaN     NaN   80.684300
50%               2025-08-11 00:00:00          NaN     NaN  101.840238
75%               2025-08-21 12:00:00          NaN     NaN  124.249732
max               2025-08-30 00:00:00          NaN     NaN  168.092639
std                               NaN          NaN     NaN   30.223144

In [58]:
print(messy["category"].unique())
print(messy["channel"].unique())

['Home' 'Electronics' 'Fashion' 'Groceries' 'Beauty' 'Unknown']
['Email' 'Search' 'App' 'Web' 'Unknown' 'Affiliate']

In [59]:
messy.head(20)

         date     category  channel     revenue
0  2025-08-01         Home    Email  152.921570
1  2025-08-02  Electronics    Email  112.004716
2  2025-03-08  Electronics   Search  129.362140
3         NaT      Fashion    Email  167.226796
4  2025-08-05    Groceries   Search  156.026740
5  2025-08-06  Electronics   Search   70.681664
6  2025-08-07    Groceries    Email  128.502653
7  2025-08-08  Electronics    Email   95.459284
8         NaT  Electronics    Email   96.903434
9  2025-08-10  Electronics    Email  112.317955
10 2025-08-11       Beauty   Search  104.321307
11 2025-08-12  Electronics      App  143.628205
12        NaT      Fashion    Email  122.831132
13        NaT      Fashion      Web  103.650250
15 2025-08-16         Home    Email  110.010230
16 2025-08-17  Electronics  Unknown  144.822372
18        NaT       Beauty    Email  109.392031
19 2025-08-20       Beauty      Web   74.377128
21 2025-08-22  Electronics    Email  119.608558
23        NaT      Unknown    Email   77.735049

## Findings
- Data cleaning successfully standardized dates, categories, and channels
- Extreme revenue outliers (>500) were removed; median revenue is now stable around 100
- Missing values were replaced with "Unknown" categories/channels or with median revenue
- Dataset is ready for analysis (e.g. revenue trends, category performance, channel comparisons)